version: '3.1'

services:
  moria:
    image: ghcr.io/sevenitynet/moria:latest
    ports:
      - ${PORT}:1980
    environment:
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      AUTH_TOKEN: ${AUTH_TOKEN}
    restart: on-failure
#    volumes:
#      - moria_uploads:/usr/local/bin/.uploads
#      - moria_tmp:/usr/local/bin/.tmp

volumes:
  moria_uploads: {}
  moria_tmp: {}

